version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: cda-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  contact-service:
    build: ./services/contact-service
    container_name: cda-contact
    environment:
      - PORT=3001
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=tu-correo@gmail.com
      - EMAIL_PASS=tu-app-password-de-gmail
      - EMAIL_DEST=destino@gmail.com
    expose:
      - "3001"
    restart: unless-stopped

  appointment-service:
    build: ./services/appointment-service
    container_name: cda-appointments
    env_file: ./services/appointment-service/.env
    environment:
      - MONGO_URI_ATLAS=${MONGO_URI_ATLAS:-}
    depends_on:
      - mongo
    expose:
      - "3002"
    restart: unless-stopped

  chatbot-service:
    build: ./services/chatbot-service
    container_name: cda-chatbot
    environment:
      - PORT=3003
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3002
    expose:
      - "3003"
    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: cda-gateway
    environment:
      - PORT=3000
      - CONTACT_SERVICE_URL=http://contact-service:3001
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3002
      - CHATBOT_SERVICE_URL=http://chatbot-service:3003
    ports:
      - "3000:3000"
    depends_on:
      - contact-service
      - appointment-service
      - chatbot-service
    restart: unless-stopped

volumes:
  mongo_data:
